# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71a4fa1489aa7c503700b76857eb4b1862ff9261fd044392266d51e53d21ac35d70057c32770423c898019fa8da7d2fbbc7514688ab88a78b6d75e27a7ef433a

test:
  secret_key_base: b70dc05895e5820dffc37a5158a6c0029e1ad75613f0328d22213f2693a2fc27771ab8f024694a0b8ed8a5d331dae6afc7eb1d45f30d6eca2cd1bea0fee278e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
